export const MAP_CONFIG = {
  center: [127.5, 36.5],
  zoom: 6,
  minZoom: 5,
  maxZoom: 16,
  maxBounds: [
    [116, 26],
    [139, 44],
  ],
}

export const BASEMAP_OPTIONS = [
  {
    id: 'standard',
    label: 'Standard',
    thumbnail: '/basemap-thumbs/standard.png',
    style: 'mapbox://styles/mapbox/standard',
    config: {
      showPlaceLabels: false,
      showPedestrianRoads: false,
      showPointOfInterestLabels: false,
      showRoadLabels: false,
      show3dObjects: false,
      show3dBuildings: false,
      show3dTrees: false,
      show3dLandmarks: false,
      showIndoorLabels: false,
      theme: 'faded',
      font: 'Noto Sans CJK JP',
      colorWater: '#88bedd',
      colorGreenspace: '#c5dcb8',
      colorRoads: 'hsla(0, 0%, 88%, 0.2)',
    },
  },
  {
    id: 'dark',
    label: 'Dark',
    thumbnail: '/basemap-thumbs/dark.png',
    style: 'mapbox://styles/mapbox/standard',
    config: {
      showPlaceLabels: false,
      showPedestrianRoads: false,
      showPointOfInterestLabels: false,
      showRoadLabels: false,
      show3dObjects: false,
      show3dBuildings: false,
      show3dTrees: false,
      show3dLandmarks: false,
      showIndoorLabels: false,
      showAdminBoundaries: true,
      lightPreset: 'day',
      theme: 'monochrome',
      font: 'Noto Sans CJK JP',
      colorLand: '#747672',
      colorWater: '#5f6364',
      colorGreenspace: '#686e66',
      colorAdminBoundaries: '#d2d5d0',
      colorRoads: 'hsla(0, 0%, 72%, 0.42)',
      colorMotorways: 'hsla(0, 0%, 78%, 0.52)',
      colorTrunks: 'hsla(0, 0%, 75%, 0.48)',
    },
  },
  {
    id: 'satellite',
    label: 'Satellite',
    thumbnail: '/basemap-thumbs/satellite.png',
    style: 'mapbox://styles/mapbox/standard-satellite',
    config: {
      showPlaceLabels: false,
      showPointOfInterestLabels: false,
      showRoadLabels: false,
      font: 'Noto Sans CJK JP',
    },
  },
]
