// 이 레이어들은 공유 레이어 레지스트리(features/map/layerActions.js)에 연동됨.
// id 추가/삭제 시 layerActions.test.js 커버리지 테스트가 동기화를 강제한다.
export const AVIATION_WFS_LAYERS = [
  {
    id: 'fir',
    nameKo: 'FIR',
    nameEn: 'FIR',
    sourceId: 'wfs-fir',
    maskLayerId: 'wfs-fir-outside-mask',
    fillLayerId: 'wfs-fir-fill',
    lineLayerId: 'wfs-fir-line',
    tickLayerId: 'wfs-fir-ticks',
    externalLabelLayerId: 'wfs-fir-external-labels',
    internalLabelLayerId: 'wfs-fir-internal-labels',
    typeName: 'lt_c_aisfirc',
    dataUrl: '/data/fir.geojson',
    fillRole: 'incheon-fir',
    lineRole: 'incheon-fir-boundary',
    color: '#1485d4',
    defaultVisible: true,
    fillOpacity: 0,
    lineOpacity: 0.9,
    lineWidth: 2,
    tickIconId: 'fir-boundary-tick',
    innerTickIconId: 'fir-boundary-inner-tick',
    tickSpacing: 42,
    innerTickSpacing: 67,
    neighborBoundaries: [
      {
        id: 'pyongyang',
        tickLayerId: 'wfs-fir-pyongyang-ticks',
      },
      {
        id: 'shanghai',
        tickLayerId: 'wfs-fir-shanghai-ticks',
      },
      {
        id: 'fukuoka',
        tickLayerId: 'wfs-fir-fukuoka-ticks',
      },
    ],
  },
  {
    id: 'sector',
    nameKo: 'Sector',
    nameEn: 'Sector',
    sourceId: 'aviation-sectors',
    fillLayerId: 'aviation-sectors-fill',
    hoverLayerId: 'aviation-sectors-hover',
    lineLayerId: 'aviation-sectors-line',
    labelLayerId: 'aviation-sectors-labels',
    dataUrl: '/data/sectors.geojson',
    color: '#2563eb',
    defaultVisible: false,
    fillOpacity: 0,
    lineOpacity: 0.7,
    lineWidth: 1.2,
  },
  {
    id: 'waypoint',
    nameKo: 'Waypoint',
    nameEn: 'Waypoint',
    sourceId: 'aviation-waypoints',
    pointMaskLayerId: 'aviation-waypoints-route-gap',
    pointLayerId: 'aviation-waypoints-point',
    pointLabelLayerId: 'aviation-waypoints-label',
    dataUrl: '/data/waypoints.geojson',
    color: '#0f766e',
    defaultVisible: false,
    pointRadius: 3,
    pointMaskRadius: 8,
    iconSize: 0.64,
    iconImageByProperty: {
      property: 'symbolType',
      fallback: 'rnav-waypoint-flyby',
      values: {
        'conventional-intersection-flyby': {
          imageId: 'symbol-intersection-conventional-flyby',
          url: '/Symbols/waypoint-conventional-flyby.svg',
        },
        'conventional-intersection-flyover': {
          imageId: 'symbol-intersection-conventional-flyover',
          url: '/Symbols/waypoint-conventional-flyover.svg',
        },
        'rnav-waypoint-flyby': {
          imageId: 'symbol-waypoint-rnav-flyby',
          url: '/Symbols/waypoint-rnav-flyby.svg',
        },
        'rnav-waypoint-flyover': {
          imageId: 'symbol-waypoint-rnav-flyover',
          url: '/Symbols/waypoint-rnav-flyover.svg',
        },
      },
    },
  },
  {
    id: 'navaid',
    nameKo: 'NAVAID',
    nameEn: 'NAVAID',
    sourceId: 'aviation-navaids',
    pointMaskLayerId: 'aviation-navaids-route-gap',
    pointLayerId: 'aviation-navaids-point',
    pointLabelLayerId: 'aviation-navaids-label',
    dataUrl: '/data/navaids.geojson',
    color: '#7c3aed',
    defaultVisible: false,
    pointRadius: 4,
    pointMaskRadius: 9,
    iconSize: 0.9,
    iconImageByProperty: {
      property: 'type',
      fallback: 'VORTAC',
      values: {
        VORTAC: {
          imageId: 'symbol-vortac',
          url: '/Symbols/navaid-vortac.svg',
        },
        'VOR/DME': {
          imageId: 'symbol-vor-dme',
          url: '/Symbols/navaid-vor-dme.svg',
        },
        TACAN: {
          imageId: 'symbol-tacan',
          url: '/Symbols/navaid-tacan.svg',
        },
      },
    },
  },
  {
    id: 'airport',
    nameKo: 'Airport',
    nameEn: 'Airport',
    sourceId: 'aviation-airports',
    pointLayerId: 'aviation-airports-point',
    dataUrl: '/data/airports.geojson',
    color: '#be123c',
    defaultVisible: true,
    pointRadius: 4,
    iconSize: 0.9,
    iconImageByProperty: {
      property: 'airportUse',
      fallback: 'civil',
      values: {
        civil: {
          imageId: 'symbol-airport-civil',
          url: '/Symbols/airport-civil.svg',
        },
        joint: {
          imageId: 'symbol-airport-joint',
          url: '/Symbols/airport-joint.svg',
        },
        military: {
          imageId: 'symbol-airport-military',
          url: '/Symbols/airport-military.svg',
        },
      },
    },
  },
  {
    id: 'ctr',
    nameKo: 'CTR',
    nameEn: 'CTR',
    sourceId: 'wfs-ctr',
    fillLayerId: 'wfs-ctr-fill',
    lineLayerId: 'wfs-ctr-line',
    typeName: 'lt_c_aisctrc',
    dataUrl: '/data/ctr.geojson',
    color: '#2563eb',
    lineDasharray: [2, 1.5],
    defaultVisible: false,
    fillOpacity: 0.04,
    lineOpacity: 0.85,
    lineWidth: 1.5,
  },
  {
    id: 'tma',
    nameKo: 'TMA',
    nameEn: 'TMA',
    sourceId: 'wfs-tma',
    fillLayerId: 'wfs-tma-fill',
    lineLayerId: 'wfs-tma-line',
    typeName: 'lt_c_aistmac',
    dataUrl: '/data/tma.geojson',
    color: '#0891b2',
    defaultVisible: false,
    fillOpacity: 0.03,
    lineOpacity: 0.85,
    lineWidth: 1.5,
  },
  {
    id: 'restricted',
    nameKo: 'Restricted',
    nameEn: 'Restricted',
    sourceId: 'wfs-restricted',
    fillLayerId: 'wfs-restricted-fill',
    lineLayerId: 'wfs-restricted-line',
    typeName: 'lt_c_aisresc',
    dataUrl: '/data/restricted.geojson',
    color: '#dc2626',
    defaultVisible: false,
    fillOpacity: 0.05,
    lineOpacity: 0.9,
    lineWidth: 1.5,
  },
  {
    id: 'prohibited',
    nameKo: 'Prohibited',
    nameEn: 'Prohibited',
    sourceId: 'wfs-prohibited',
    fillLayerId: 'wfs-prohibited-fill',
    lineLayerId: 'wfs-prohibited-line',
    typeName: 'lt_c_aisprhc',
    dataUrl: '/data/prohibited.geojson',
    color: '#dc2626',
    defaultVisible: false,
    fillOpacity: 0.06,
    lineOpacity: 0.9,
    lineWidth: 1.7,
  },
  {
    id: 'danger',
    nameKo: 'Danger',
    nameEn: 'Danger',
    sourceId: 'wfs-danger',
    fillLayerId: 'wfs-danger-fill',
    lineLayerId: 'wfs-danger-line',
    typeName: 'lt_c_aisdngc',
    dataUrl: '/data/danger.geojson',
    color: '#dc2626',
    defaultVisible: false,
    fillOpacity: 0.05,
    lineOpacity: 0.9,
    lineWidth: 1.5,
  },
  {
    id: 'ats-route',
    nameKo: 'ATS Route',
    nameEn: 'ATS Route',
    sourceId: 'wfs-airway',
    lineLayerId: 'wfs-ats-route-line',
    routeLabelLayerId: 'wfs-ats-route-label',
    typeName: 'lt_l_aispath',
    dataUrl: '/data/airways.geojson',
    color: '#1f2933',
    routePrefixFilter: ['!', ['in', ['slice', ['get', 'ident_txt'], 0, 1], ['literal', ['L', 'Y', 'Z']]]],
    defaultVisible: false,
    lineOpacity: 0.9,
    lineWidth: 1.4,
  },
  {
    id: 'rnav-route',
    nameKo: 'RNAV Route',
    nameEn: 'RNAV Route',
    sourceId: 'wfs-airway',
    lineLayerId: 'wfs-rnav-route-line',
    routeLabelLayerId: 'wfs-rnav-route-label',
    typeName: 'lt_l_aispath',
    dataUrl: '/data/airways.geojson',
    color: '#0076c8',
    routePrefixFilter: ['in', ['slice', ['get', 'ident_txt'], 0, 1], ['literal', ['L', 'Y', 'Z']]],
    defaultVisible: false,
    lineOpacity: 0.9,
    lineWidth: 1.4,
  },
]
