// 디자인 토큰 단일 소스 (JS). 지도/canvas/WebGL/SVG 등 CSS 변수를 못 쓰는 곳에서 사용.
// tokens.css(:root)와 1:1 일치 (tokens.test.js가 강제). 헌법: docs/design/design-language.md §5
export const CSS_VARS = {
  '--space-none': '0',
  '--space-xxs': '2px',
  '--space-xs': '4px',
  '--space-snudge': '6px',
  '--space-s': '8px',
  '--space-mnudge': '10px',
  '--space-m': '12px',
  '--space-l': '16px',
  '--space-xl': '20px',
  '--space-xxl': '24px',
  '--space-xxxl': '32px',
  '--font-base': "'Pretendard GOV', system-ui, sans-serif",
  '--app-font': 'var(--font-base)',
  '--fs-100': '10px',
  '--fs-200': '12px',
  '--fs-300': '14px',
  '--fs-400': '16px',
  '--fs-500': '20px',
  '--fs-600': '24px',
  '--fs-700': '28px',
  '--fs-800': '32px',
  '--fs-900': '40px',
  '--lh-100': '14px',
  '--lh-200': '16px',
  '--lh-300': '20px',
  '--lh-400': '22px',
  '--lh-500': '28px',
  '--lh-600': '32px',
  '--lh-700': '36px',
  '--lh-800': '40px',
  '--lh-900': '52px',
  '--fw-regular': '400',
  '--fw-medium': '500',
  '--fw-semibold': '600',
  '--fw-bold': '700',
  '--radius-none': '0',
  '--radius-sm': '2px',
  '--radius-md': '4px',
  '--radius-lg': '6px',
  '--radius-xl': '8px',
  '--radius-circular': '9999px',
  '--text-1': '#242424',
  '--text-2': '#424242',
  '--text-3': '#616161',
  '--text-disabled': '#bdbdbd',
  '--bg-1': '#ffffff',
  '--bg-2': '#fafafa',
  '--bg-3': '#f5f5f5',
  '--bg-4': '#f0f0f0',
  '--bg-5': '#ebebeb',
  '--stroke-1': '#d1d1d1',
  '--stroke-2': '#e0e0e0',
  '--stroke-strong': '#616161',
  '--accent': '#334155',
  '--level-green': '#166534',
  '--level-green-bg': '#dcefe2',
  '--level-amber': '#92400e',
  '--level-amber-bg': '#fdecc8',
  '--level-red': '#c0291f',
  '--level-red-bg': '#f7dcd9',
  '--level-gray': '#475569',
  '--level-gray-bg': '#eef2f7',
  '--cat-vfr': '#166534',
  '--cat-mvfr': '#1d4ed8',
  '--cat-ifr': '#c0291f',
  '--cat-lifr': '#9d2c9d',
  '--icing-1': '#ACC7FF',
  '--icing-2': '#6B88CD',
  '--icing-3': '#383D6F',
  '--turb-light': '#64D264',
  '--turb-mod': '#FFC300',
  '--turb-sev': '#FF3737',
}

const C = CSS_VARS

// 구조화 접근자 (CSS_VARS에서 파생 — JS 내부 드리프트 없음)
export const space = {
  none: C['--space-none'], xxs: C['--space-xxs'], xs: C['--space-xs'], snudge: C['--space-snudge'],
  s: C['--space-s'], mnudge: C['--space-mnudge'], m: C['--space-m'], l: C['--space-l'],
  xl: C['--space-xl'], xxl: C['--space-xxl'], xxxl: C['--space-xxxl'],
}

export const color = {
  text1: C['--text-1'], text2: C['--text-2'], text3: C['--text-3'], textDisabled: C['--text-disabled'],
  bg1: C['--bg-1'], bg2: C['--bg-2'], bg3: C['--bg-3'], bg4: C['--bg-4'], bg5: C['--bg-5'],
  stroke1: C['--stroke-1'], stroke2: C['--stroke-2'], strokeStrong: C['--stroke-strong'], accent: C['--accent'],
  level: {
    green: C['--level-green'], greenBg: C['--level-green-bg'],
    amber: C['--level-amber'], amberBg: C['--level-amber-bg'],
    red: C['--level-red'], redBg: C['--level-red-bg'],
    gray: C['--level-gray'], grayBg: C['--level-gray-bg'],
  },
  cat: { vfr: C['--cat-vfr'], mvfr: C['--cat-mvfr'], ifr: C['--cat-ifr'], lifr: C['--cat-lifr'] },
  // icing[grade]: 0=투명(없음), 1~3
  icing: [null, C['--icing-1'], C['--icing-2'], C['--icing-3']],
  turb: { light: C['--turb-light'], mod: C['--turb-mod'], sev: C['--turb-sev'] },
}
